### ISSUE TITLE
Add support for Windows

### ISSUE THREAD

**Issue by sole** [mozilla/node-firefox-find-ports#1]

**Comment by lmorchard** [comment]
If @tofumatt isn't already tackling this, I can give it a shot!

**Comment by tofumatt** [comment]
I’m not in the middle of it, and I am a Windows newbie! Go ahead, and I’ll review! :-)

-tofumatt

On 23 January 2015 at 14:51:24, Les Orchard (notifications@github.com) wrote:

If @tofumatt isn't already tackling this, I can give it a shot!

**Comment by lmorchard** [comment]
Some notes mainly to myself, but in case I have bad luck with a bus: 

It looks like it's possible to look up processes & open listening ports in Windows, but not all in the same command. So, I'm going to need to make a call to `tasklist.exe` to find firefox & b2g. Then, I can match up the pids to the output of `netstat.exe -ano`

**Comment by nicola** [comment]
Sorry for being late in this conversation. I was very close to implementing that, but I decided to be more prolific and experimental than providing support to multiple platform.

If I don't remember it wrongly, there are two commands you need to exec and @lmorchard describes exactly that the strategy (the only way I found as well). Good luck!
