### ISSUE TITLE
Why is the license apache?

### ISSUE THREAD

**Issue by erikvold** [mozilla/node-firefox-find-ports#31]
I thought all mozilla projects should be mpl 2 by default.  Why is this project not mpl 2?

**Comment by tofumatt** [comment]
Speaking for myself: Apache 2 is a less complex license, more permissive, and more in line with the node.js community which favours MIT/Apache 2.0.

While MPL 2 is not strong copyleft, it’s still confusing for lots of people who just want to use free software and don’t understand how MPL works.

**Comment by tofumatt** [comment]
Additionally, I recall Gerv saying it was fine for us to use permissive, non-copyleft licenses in our web dev projects back in the day (things like Python sites/playdoh), but that we should just use Apache 2.0 as it has the patent protection clauses.

**Comment by sole** [comment]
Here: https://github.com/mozbrick/brick/issues/60#issuecomment-26619977

**Comment by fwenzel** [comment]
Mozilla projects are either MPL2 or Apache, in accordance with Mozilla's licensing policy :) https://www.mozilla.org/MPL/license-policy.html

Hope this helps!

**Comment by fwenzel** [comment]
(Oh, I suppose I just quoted myself. Heh.)
